# Generated by Django 5.2.5 on 2025-08-11 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_income'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='text',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='text',
            new_name='title',
        ),
    ]
